### ISSUE TITLE
Need Future Econ logo added to site

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#1]

**Comment by lmilholland** [comment]
I see the logo now when I scroll through stories at the top! Still missing from the landing page. 
![2015-01-22 14_32_40-greenshot](https://cloud.githubusercontent.com/assets/10564459/5866148/95975cc8-a243-11e4-9f85-86047b7b0c61.png)

**Comment by ghost** [comment]
Added the logo there.

Also fixed the spacing of the white floating header and the About button in the top right.
