### ISSUE TITLE
Spacing between paragraphs, safari and chrome, pc

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#10]
The spacing between paragraphs is not consistent - sometimes it's tighter than other times. I'm not sure if that's a problem in how we entered the story or something structurally wrong. Can you please check? 
![2015-01-16 15_50_11-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786305/9193e656-9d97-11e4-97e4-e9d3e515384f.jpg)

**Comment by ghost** [comment]
I did not do anything to affect that - so it's probably left over from the commonplace theme and how the content was entered.  I can definitely fix any inconsistencies with spacing _after_ content has been entered.
