### ISSUE TITLE
Sentinel in body text, safari, pc

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#11]
Sentinel is not appearing in the body text in my safari browser. It is appearing in chrome. 
![2015-01-16 15_56_26-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786353/69c943fe-9d98-11e4-9317-0b2d14bf6033.jpg)

**Comment by ghost** [comment]
Font issues should be fixed.

Y'all were probably wondering if I had actualy done ANYTHING. ^_^ I assure you I did, just needed to update the domain name on typography.com.
