### ISSUE TITLE
Links, safari, chrome, pc 

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#12]
Links are not showing up in orange sentinel black, but rather in orange ariel, I think. 
![2015-01-16 15_58_19-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786367/af50071e-9d98-11e4-8343-504e5c14b31b.jpg)
![2015-01-16 15_58_57-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786366/af4fe90a-9d98-11e4-968e-d89fc8fec176.jpg)

**Comment by ghost** [comment]
Now that the fonts are fixed, it looks like the body content is Sentinel and the links are actually Knockout - is it not supposed to be this way?

**Comment by sarahmagrish** [comment]
Links should just be bold orange Sentinel - thx!

## 

Sarah Cline | Design Director | Ecotrust
721 NW 9th Avenue, Suite 200 |  Portland, OR 97209
M (971) 344.7595 | www.ecotrust.orghttp://www.ecotrust.org/

Please note that my office hours are Monday, Tuesday & Wednesday.

**Comment by lmilholland** [comment]
Meant to say, links are orange! And bold. But not yet sentinel. 
![2015-01-22 14_30_41-greenshot](https://cloud.githubusercontent.com/assets/10564459/5866668/5a426cb2-a248-11e4-9a51-f655fcf640f9.png)

**Comment by ghost** [comment]
Fixed.
