### ISSUE TITLE
pop-ups from sidebars, safari, pc

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#13]
This may have more to do with the overall problem with sidebar content, but I believe it should be clickable and open a pop-up that hovers over the page. Currently, I'm getting an error message. See bottom of screen. Here is the same thing on commonplace. 
![2015-01-16 16_06_11-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786441/e19c66a8-9d99-11e4-9691-f41eb48c6bfb.jpg)
![2015-01-16 16_07_42-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786442/e19ded02-9d99-11e4-9c8c-05537d681e16.jpg)
![2015-01-16 16_07_53-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786440/e199a134-9d99-11e4-858b-303d3fc4d23c.jpg)

**Comment by ghost** [comment]
Yeah - again, that's because the image / gallery content was not carted over with the commonplace placeholder content.

**Comment by ghost** [comment]
Is this still happening?

**Comment by lmilholland** [comment]
Sorry! I will test it now.

**Comment by lmilholland** [comment]
Looks great! i added content and seems to be no problem.
