### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#14]
I believe this is lacking images for the obvious reason that we didn't pull them over from the other site. Should I try uploading some images in both the sidebar and main body to test? Please let me know when you're ready for me to try that out.

Thanks!

**Comment by ghost** [comment]
Yes. If you want to see what it looks like you'll have to cart over the images form commonplace. I did just that on the homepage and the first story "On Family" I think it is...
