### ISSUE TITLE
Bold text, safari, chrome, pc 

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#15]
Bold text, as in the case of these questions, does not appear to be in the same font as the main body text. See future economy and commonplace for comparison.
![2015-01-16 16_12_11-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786472/97980dc2-9d9a-11e4-8f18-b9d1d535020e.jpg)
![2015-01-16 16_12_18-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786471/978d37a8-9d9a-11e4-862f-315961c0c9d6.jpg)

**Comment by ghost** [comment]
See if this is fixed now that the fonts are being pulled in.
