### ISSUE TITLE
About link, upper right, safari, chrome, pc

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#16]
We seem to be missing the About link in the upper right corner of the screen. Including screen shots of future economy and commonplace for reference.
![2015-01-16 16_14_37-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786485/e52128d0-9d9a-11e4-8d89-d5b4912f004e.jpg)
![2015-01-16 16_14_44-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786486/e5221b32-9d9a-11e4-9e9d-092b716ccde7.jpg)

**Comment by ghost** [comment]
Okay. Looks like I got it showing up - but (probably because I added the logo and adjusted the height of the top nav bar) - it's not showing up right. I'll fix that. This bug is not closed yet!

**Comment by ghost** [comment]
Fixed.
