### ISSUE TITLE
Sidebar - audio, safari, chrome, pc 

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#17]
The audio sidebar content does appear! But for some reason it links back to the start of the story in which it's placed. 
![2015-01-16 16_18_22-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786514/691d468c-9d9b-11e4-85fc-b6804deed038.png)

**Comment by ghost** [comment]
Again, probably an issue with multimedia content not being carted over from commonplace.

**Comment by lmilholland** [comment]
I tested the video - works great. I tested audio, and it also works great. But for some reason the words "audio player" are appearing below the sidebar. Ideas? 
![2015-01-23 16_28_27-greenshot](https://cloud.githubusercontent.com/assets/10564459/5885189/13541ae6-a31d-11e4-9241-1cb31caf642d.png)

**Comment by ghost** [comment]
Probably programmed that way - I can remove it if you want... ?

**Comment by lmilholland** [comment]
Yes, please remove! I looked at Commonplace and it wasn't there, so who knows!

**Comment by ghost** [comment]
Weird.  Well I hid that container, so it shouldn't show. 

My best guess is that there is some sort of plugin or auto-embed magic that is turning the <audio> tag into a styled audio player and it's adding that Audio Player text. 

It's gone now.

**Comment by lmilholland** [comment]
I still see it. Do I need to do some special form of refresh?

**Comment by ghost** [comment]
Yeah, maybe.   

If you are logged in and on the page - Is there a WordPress admin toolbar along the bottom of the screen?  If so - look for “Flush Cache” and click that. Then when the page reloads, hit reload on the browser.  Should be gone. After doing that, let me know if it’s still there.

Thanks.  

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)

**Comment by lmilholland** [comment]
Awesome, thank you!
