### ISSUE TITLE
Dek/subhead in TOC

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#18]
Hey Sarah,

Can you give Jim directions on the dek/subhead style for the Table of Contents? I'd love to add that element to the Future Economy site as an enhancement from Commonplace. Here is example text:

Hed: Who’s sharing economy is it? 
Dek: One economist surfs couches and parses the literature to figure out who the exploding sharing economy is really benefiting.

**Comment by sarahmagrish** [comment]
How does this feel? The dek is Sentinel Book, 13/15, tracked out 50pt, black.

![screen shot 2015-01-26 at 1 07 19 am](https://cloud.githubusercontent.com/assets/4765127/5897334/b9eeb60a-a4f7-11e4-95ab-e6e08377e5bc.png)

**Comment by lmilholland** [comment]
I think that looks great! Again, Jim, is this enough direction for you to jump in and add a dek to the home page table of contents?

**Comment by ghost** [comment]
yep! No problem. I'll have that for you soon!

**Comment by ghost** [comment]
Okay. I added that to the homepage stories (go to the homepage, and under each story, find the new field "Homepage Excerpt".  Enter the excerpt there and it will appear in the table of contents as requested.

![edit_page_ _future_economy_ _wordpress](https://cloud.githubusercontent.com/assets/886931/5906618/eef0fb8c-a54d-11e4-8a41-a81c06418938.png)
