### ISSUE TITLE
Sidebar heds not in knockout - safari, pc

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#19]
The sidebar content looks good - no longer bonkers code! But the font is not kn
![2015-01-22 14_27_22-greenshot](https://cloud.githubusercontent.com/assets/10564459/5866232/4a6aa34e-a244-11e4-864f-991d950f2c1a.png)
ockout htf51 15pt.

**Comment by ghost** [comment]
Okay. I think I have this right now.
