### ISSUE TITLE
Knockout

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#2]
Knockout is displaying funny on my Mac in Chrome - it is clear that it is loading and it has the same name  when i look at the CSS but visually the weights are really different. Screenshots attached. This seems to apply across the board - not just the heds. LMK if this is unclear - we can do this over the phone or in person.

Could the web font and desktop font be rendering this different? What do you think is happening? 
![screen shot 2015-01-15 at 6 53 14 pm](https://cloud.githubusercontent.com/assets/4765127/5770909/11741d60-9ce8-11e4-9179-521b351c0e57.png)
![screen shot 2015-01-15 at 6 55 50 pm](https://cloud.githubusercontent.com/assets/4765127/5770919/3248895e-9ce8-11e4-8686-14551d6cc875.png)

**Comment by lmilholland** [comment]
On my pc, in both safari and chrome, Knockout is not appearing at all.

**Comment by ghost** [comment]
Yeah, I needed to add futureecon.org as another domain in typography.com.  Only had my dev environment domain name there.  

Updated - you should see the fonts properly now.

![cloud_typography_project__future_economy](https://cloud.githubusercontent.com/assets/886931/5808595/0301c288-9fe4-11e4-8191-7ea420521d05.png)
