### ISSUE TITLE
Photo gallery titles and subtitles

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#20]
I think the fonts and styles aren't pulling correctly. Should be:

Title:
OPTIONAL TITLE KNOCKOUT HTF51 44 PT.
Under the orange line / subtitle:
Sentinel Italic 14pt, tracked out 50 pt

(And would you please check if the image captions are Sentinel Book, 14pt over 22pt, tracked out 50pt.)

**Comment by ghost** [comment]
Fixed.
