### ISSUE TITLE
Author name and bio 

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#21]
Sarah, I don't see directions on the style sheet for the author name and bio at the end of the storeis. Can you please direct? I think we dno't want the bio text in bold, for example. Thanks! 
![2015-01-22 14_29_26-greenshot](https://cloud.githubusercontent.com/assets/10564459/5866633/0afcca6c-a248-11e4-921d-e2e58fa0a98e.png)

**Comment by sarahmagrish** [comment]
Sure thing - let's leave author name as is and change bio to Sentinel Book Italic, 14/20, tracked out 25, black. work for you?

**Comment by lmilholland** [comment]
Works for me! Jim, see Sarah's direction on author bio style. Thanks!

**Comment by ghost** [comment]
Okay. Done.

**Comment by sarahmagrish** [comment]
oops - looks like the bio is still knockout - should be Sentinel Book Italic, 14/20, tracked out 25, black.
