### ISSUE TITLE
Categories in wordpress posts

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#22]
I'm adding content and wondering about the "categories" section. Do I need to click "New Pioneers" for the stories to end up on this site? Could I create a "Future Economy" category, and would it pull that content onto the site? Please advise. Thanks!

**Comment by ghost** [comment]
Yeah you should probably create a Future Economy category - but I'm not sure 100% how it's all wired up and connected.  I think you actually edit that "New Pioneers" page to add the various articles.

Again, I think a 30-60 minute sit down to go over how the theme works and how the backend is setup might be useful.
