### ISSUE TITLE
Image behind title - wordpress backend

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#23]
I am not able to upload an image behind the title card. The edit image button shows up when I hover over an innocuous square (where I think the media button should be) but then once the pop up is open, I still can't upload anything. Help! 
![2015-01-22 17_16_01-greenshot](https://cloud.githubusercontent.com/assets/10564459/5868150/970c9fca-a25a-11e4-9d0c-1a6e93f8c7a9.png)
![2015-01-22 17_17_01-greenshot](https://cloud.githubusercontent.com/assets/10564459/5868151/97f6654c-a25a-11e4-960f-fff46d1a0b25.png)

**Comment by ghost** [comment]
You need to click on the little X that shows up when you hover over it. It thinks there should be an image there but the image / media was never uploaded.  So click the X - then you should see a button to "Upload Image" click that to upload or select the image you want to use.

**Comment by lmilholland** [comment]
Thanks, Jim! I totally see that I was being block-headed. Solved this problem.
