### ISSUE TITLE
block quotes versus headers - the styles may be too similar.

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#24]
Sarah, block quotes are looking a little too similar to section headers! I think Jim has them correct - based on what I'm seeing on the style sheet. Thoughts? 
![2015-01-22 17_31_26-greenshot](https://cloud.githubusercontent.com/assets/10564459/5868326/94608046-a25c-11e4-8f25-b471eac2fcbd.png)
![2015-01-22 17_31_33-greenshot](https://cloud.githubusercontent.com/assets/10564459/5868327/9524bdd0-a25c-11e4-85b7-9c403a348f48.png)

**Comment by sarahmagrish** [comment]
yep, they are following the stylesheet and agreed, they are too close! What if we tried them as sentence case and orange? Might be nice to have that pop of color...

**Comment by lmilholland** [comment]
Totally agree! Jim, is that enough direction to make that change? Please update pull quotes to sentence case and orange.

**Comment by ghost** [comment]
Okay, how is that? http://futureecon.org/future-economy/fighting-poverty-with-parks/
