### ISSUE TITLE
"feature image"

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#25]
I tried to add a feature image in the post, and it didn't show up in the TOC or the story, but it did shoot out a bunch of crazy code in the story. And after I had uploaded it, the image I had successfully loaded into the story previously vanished! 
![2015-01-22 17_38_43-greenshot](https://cloud.githubusercontent.com/assets/10564459/5868412/c09cd8e8-a25d-11e4-888c-9c9557d12656.png)
![2015-01-22 17_39_00-greenshot](https://cloud.githubusercontent.com/assets/10564459/5868414/c23c6fec-a25d-11e4-9ce1-0b246235c31c.png)

**Comment by lmilholland** [comment]
Nevermind about the image in the story. It reappeared. But there's still crazy code at top from the "featured image"

**Comment by ghost** [comment]
Yeah I ran into this the other day - It looked like in the code there was an error / bug where it is supposed to use the featured image IF you don't input a Header background image - but the code is not setup right so that if you do this it throws those errors. I can fix it.
