### ISSUE TITLE
listing in sidebar and Table of Contents

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#26]
I think I solved the featured image issue in that I started a brand new post and uploaded images smoothly! But now that post (http://futureecon.org/future-economy/whose-sharing-economy/) is not appearing in the sidebar or homepage table of contents. Can you please help me place it there? Thanks!

**Comment by ghost** [comment]
Again, I think a sit down would be helpful. But you have to edit the New Pioneers page and edit the custom fields under Stories to tell that page which stories to display and in what order.
