### ISSUE TITLE
Question: What should I do with the previous commonplace posts?

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#27]
I deleted a few to see if it influenced teh homepage and sidebar TOC and I see that it doesn't. Please let me know what do to with that content now that (finally) I have new content to add. Thanks!

**Comment by ghost** [comment]
It doesn't totally matter if you "replace" content or if you "create new" as long as it is done in the right way. In other words, the theme was setup in such a way that it expects certain information and fields filled out on the pages / posts.  You'll want to make sure you set it up correctly.  Again, I think if we sat down together I could show you how it's supposed to be setup and what fields you need to focus on.

**Comment by lmilholland** [comment]
It's probably not a bad idea. It turns out that I did a lot on commonplace - but not the table of contents. (That was in Sarah's hands.) However, Oakley briefly showed me where I can make some of those changes. I'm going to play this afternoon, but if you have time on Monday, would it make sense to sit down together? I'm free before 11 and from noon to 2. Sarah is so swamped with other work that I suspect I will be doing a lot of this work.
