### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#28]
I'm beginning to wonder if the logo should be big and the only thing you see on the landing page. Otherwise, do we need a title in addition to Future Economy? Oakley and I think that's probably enough, but please weigh in with your perspective and then we can direct Jim to make that change. 

(Ignore the strawberry photo. Just wanted to mix it up and a temp image. The real versus rhetoric is also placeholder, and I think we'll want the Issue 2 line removed.) 
![2015-01-23 15_25_33-greenshot](https://cloud.githubusercontent.com/assets/10564459/5884549/24cac4a4-a314-11e4-828b-a33455750bee.png)

**Comment by sarahmagrish** [comment]
yes, the def shouldn't say the same thing! And issue should be pulled. But should it have another title? I am on the fence. I guess it depends on what we might be able to / want to say there? Talk more tomorrow?

**Comment by lmilholland** [comment]
Totally! I want to bring Oakley into the discussion. He basically said: Get rid of the text. Just have the logo. But let's talk about what the two options offer at our meeting!
