### ISSUE TITLE
Author & photographer names are in Sentinel Bold, 26 pt, 50 tracking

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#3]
Currently not rendering that way. See screenshot.
![screen shot 2015-01-15 at 6 55 50 pm](https://cloud.githubusercontent.com/assets/4765127/5770930/7b528668-9ce8-11e4-9b5d-124275bf8983.png)

**Comment by ghost** [comment]
Check now. Updated font domain on typography.com

**Comment by lmilholland** [comment]
I'm not seeing the author and photographer name in sentinel in safaru - pc. Might be knockout? 
![2015-01-22 14_34_53-greenshot](https://cloud.githubusercontent.com/assets/10564459/5866197/f4a681a8-a243-11e4-8fa5-bc0a93d181de.png)

**Comment by ghost** [comment]
I'll look into this - in general, y'all should install the WhatFont extension for google chrome.  It allows you to activate and then hover over text to see detailed imforation about what font is displaying and at what size.

**Comment by ghost** [comment]
Fixed.
