### ISSUE TITLE
Remove issues list and enews sign up on the bottom of the about page

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#30]
I think Will added a feature that would list all of the commonplace issues to the bottom of the about page which is irrelevant in this iteration. Can you remove both the issues section AND the list of two issues AND the enews signup?  
![2015-01-23 15_13_43-greenshot](https://cloud.githubusercontent.com/assets/10564459/5884745/7e0c3c6c-a316-11e4-8bd4-765331d81db4.png)

**Comment by ghost** [comment]
Okay. Done.
