### ISSUE TITLE
About page - staff

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#31]
I have the power to edit who the staff are on the about page, but I wonder if we can change the text so instead of "meet the ... staff" it reads "meet the steering committee."  And then below that, it reads "Contact the Future Economy Initiative" and we have another opportunity to include people. Can you help?  
![2015-01-23 15_59_22-greenshot](https://cloud.githubusercontent.com/assets/10564459/5884897/d56c7bf0-a318-11e4-80cb-c5cca88a8ac2.png)

**Comment by ghost** [comment]
Yes. Let me see what I can do.

**Comment by ghost** [comment]
Okay. I added the ability to edit the title of those sections, and I duplicated the people section so there is no a More People section with title.

![fighting_poverty_with_parks](https://cloud.githubusercontent.com/assets/886931/5907331/0e64bc06-a553-11e4-8196-0084af499216.png)

![edit_page_ _future_economy_ _wordpress](https://cloud.githubusercontent.com/assets/886931/5907340/1e9430de-a553-11e4-8cbb-0cb9190d49f5.png)

![edit_page_ _future_economy_ _wordpress](https://cloud.githubusercontent.com/assets/886931/5907343/28b9aa6c-a553-11e4-8a93-cc80008fae99.png)
