### ISSUE TITLE
Story landing pages title text

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#35]
On my mac at home, the title text is bleeding over the photo rather than resizing with it. I think that may be an issue of the size of the text. Something to think about! Should we bring down that size? Or is there another way to fix?  
![screen shot 2015-01-26 at 8 36 26 am](https://cloud.githubusercontent.com/assets/10564459/5903441/93a75544-a536-11e4-98c2-5dc31b0a938a.png)
![screen shot 2015-01-26 at 8 43 17 am](https://cloud.githubusercontent.com/assets/10564459/5903582/677a3102-a537-11e4-9245-84b3760b70e3.png)

**Comment by ghost** [comment]
I could have a media query that changes the font-size based on the vertical height of the browser window.  That way we could attempt to keep the title inside the browser window (within reason).

**Comment by sarahmagrish** [comment]
That sounds good Jim! Could you also bring down the size a bit - that way we can get away with longer words / titles as need. Maybe 85% - just make sure you bring down font size, line and letter spacing proportionally. You ok with eyeballing it like that?

**Comment by ghost** [comment]
Okay - I decreased the size overall by 85% - and I decreased it even more on screen sizes with a height less than 800px. 

Take a look and let me know if that is better.

**Comment by lmilholland** [comment]
The text sizing looks good to me! I'll let Sarah answer as well. But the arrow has disappeared from my little screen. Somehow, the photo is elongated and the arrow is not showing me the way, but is appearing when I scroll down at the bottom. This is on my laptop. See below. Easy fix? 
![2015-01-27 13_04_11-greenshot](https://cloud.githubusercontent.com/assets/10564459/5927103/34364968-a625-11e4-9d80-78b2b95220ab.png)

**Comment by ghost** [comment]
Try reloading. Sometimes if you adjust the browsersize it doesn't update.
Let me know if that works.

On Tuesday, January 27, 2015, lmilholland notifications@github.com wrote:

> The text sizing looks good to me! I'll let Sarah answer as well. But the
> arrow has disappeared from my little screen. Somehow, the photo is
> elongated and the arrow is not showing me the way, but is appearing when I
> scroll down at the bottom. This is on my laptop. See below. Easy fix?
> [image: 2015-01-27 13_04_11-greenshot]
> https://cloud.githubusercontent.com/assets/10564459/5927103/34364968-a625-11e4-9d80-78b2b95220ab.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sarahmagrish/Future_Economy/issues/35#issuecomment-71727755
> .

## 

Jim Krill

## Web Developer

_Website: *http://www.krillwebdesign.com
*Email_: jimkrill@gmail.com
_Work Phone_: (971) 259-8164

**Comment by lmilholland** [comment]
Got it! Thank you.
