### ISSUE TITLE
futureecon.org is live, should be private

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#36]
It seems that the futureecon.org site is live to the public. Can we password protect it for now? And if I want to make it live while you're away, can you show me how? Thanks!

**Comment by ghost** [comment]
Okay. I activated a plugin called Password Protect - it’s a single password protect for WP.  

The password is “ecoTru$t2015”

Actually I think the way it works is that if you login as an admin - you should be able to see the site. Or you can enter that password.

To turn it off, just go to Settings -> Password Protect and uncheck the “enabled” checkbox (see screenshot)

Password_Protected_‹_Future_Economy_—_WordPress.png (http://cloud.krillwebdesign.com/image/2n2z3S191q40)  

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)
