### ISSUE TITLE
"Produced by Ecotrust" on bottom

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#37]
Where is the text that sits at the bottom of the homepage controlled? I want to change it, but can't seem to find it in the Future Economy page. If it's easy to tell me, please let me know where that lives and I'll change it. If it's hard, could you make the bottom of the homepage read (instead of Produced by Ecotrust, see screenshot):

A project of Ecotrust and the E3 Network

And ecotrust would be livelinked to http://www.ecotrust.org and E3 Network to http://www.e3network.org/

![screen shot 2015-01-26 at 1 14 10 pm](https://cloud.githubusercontent.com/assets/10564459/5908540/74e2c16c-a55d-11e4-8547-dbd2e3a20e18.png)

And Ecotrust is livelinked to www.ecotu

**Comment by ghost** [comment]
Okay. Updated that.

If you want, I can add this as an editable field on the Issues Landing page template (i.e. the Future Economy homepage)?

**Comment by lmilholland** [comment]
I would love that, Jim. Thank you!

**Comment by ghost** [comment]
So it looks like there was meta data for Credits and Thank you’s. Found it commented out in the code.  The custom fields are in the backend though.  

I turned it on and it looks like this:
The_Future_Economy_-_Future_Economy.png (http://cloud.krillwebdesign.com/image/2p1e251m1x3Z)

Do you want to keep it like this and use the current fields for Credits and Thank Yous?   

Or I can replace this all with a single editor that allows you to enter text that is centered like “A project by Ecotrust” was…?  

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)

**Comment by lmilholland** [comment]
I think we want the single editor for our chosen line of text. Thank you!

**Comment by ghost** [comment]
Okay,  

Go ahead and use the “Credits” custom field under the Publisher’s Letter and Credits tab on the Future Economy page to add the credits.  I’ve put in the credits as requested - but this would be how you edit it in the future.  

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)
