### ISSUE TITLE
Story Deks

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#38]
Looks like my style doesn't really fit the content - see screenshot here. Sorry about that.

![screen shot 2015-01-26 at 1 43 05 pm](https://cloud.githubusercontent.com/assets/4765127/5909103/3d776a7a-a562-11e4-8dd5-9a664d3adde7.png)

Ok if we switch that style to sentence case, 14pt font size over 20pt line height, no letterspacing? Same font and color.

Example here: 
![screen shot 2015-01-26 at 1 51 22 pm](https://cloud.githubusercontent.com/assets/4765127/5909119/71916c0c-a562-11e4-8233-d0867879267c.png)

thank you!!

**Comment by ghost** [comment]
Okay. Have a look now and see if that works.

**Comment by lmilholland** [comment]
Thanks, Jim! Sarah, I don't what you think, but now it feels so secondary - I'm not sure it's serving it's role. Might need a brand new solution, if you have time.

**Comment by sarahmagrish** [comment]
i am ok with it! do you mind if it lives for now?

**Comment by lmilholland** [comment]
totally good! time is ticking :-) plus it's grown on me.
