### ISSUE TITLE
About page enhancements

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#39]
Hi Jim, Can you make the dek on teh about page editable? Right now it says "Want to share Future Economy?" I want it to read; "Want to connect with the Future Economy Initiative?"

Also, can you add the same footer from the home page - or an editable field - at the very bottom, below the contact people photos, so I can reiterate: "A project of..." 

Lastly, can the title also be editable? It reads "Welcome to Future Economy." I think it should probably read: "About the Future Economy Initiative" 

Thanks!

![2015-01-27 13_17_21-greenshot](https://cloud.githubusercontent.com/assets/10564459/5927416/29519b90-a627-11e4-9702-2f6781aeb259.png)
![2015-01-27 13_17_00-greenshot](https://cloud.githubusercontent.com/assets/10564459/5927445/55e4664c-a627-11e4-8df7-2d909b87449e.png)

**Comment by ghost** [comment]
You got it! I'll let you know when those changes have been made.

Just a reminder, today is my last day this week - so get all your changes in before noon and I'll do my best to have them done before the end of the day.

**Comment by ghost** [comment]
Okay. You'll find a couple additional fields on the about page: Dek and Share Links (I went ahead and made those editable so you could updat the URL's or remove if they don't apply).

Also, edit the title of the page to edit that headline.

Cheers.

![edit_page_ _future_economy_ _wordpress](https://cloud.githubusercontent.com/assets/886931/5943597/29eea67a-a6d5-11e4-8d2d-288891771e26.png)
