### ISSUE TITLE
Stange code fragments

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#4]
These appear in many stories on my Mac in Chrome. I am attaching screenshots here where you can see each story name in the top left corner.
![screen shot 2015-01-16 at 12 21 41 pm](https://cloud.githubusercontent.com/assets/4765127/5783872/f82031a2-9d7b-11e4-9547-fb3f126f405c.png)
![screen shot 2015-01-16 at 12 22 09 pm](https://cloud.githubusercontent.com/assets/4765127/5783868/f81725bc-9d7b-11e4-8167-ebd9d5ecdcd0.png)
![screen shot 2015-01-16 at 12 30 17 pm](https://cloud.githubusercontent.com/assets/4765127/5783867/f81378ea-9d7b-11e4-8709-d77b3ed4b6ee.png)
![screen shot 2015-01-16 at 12 31 28 pm](https://cloud.githubusercontent.com/assets/4765127/5783871/f81faa2a-9d7b-11e4-88b8-28c3dab63eb1.png)
![screen shot 2015-01-16 at 12 31 41 pm](https://cloud.githubusercontent.com/assets/4765127/5783870/f81c783c-9d7b-11e4-874b-1ee92d3ca868.png)
![screen shot 2015-01-16 at 12 32 06 pm](https://cloud.githubusercontent.com/assets/4765127/5783869/f8178a20-9d7b-11e4-8acc-ec7a235daba6.png)
![screen shot 2015-01-16 at 12 32 25 pm](https://cloud.githubusercontent.com/assets/4765127/5783873/f8358f8e-9d7b-11e4-8e7c-2b9de9c5c4a9.png)

**Comment by ghost** [comment]
Probably because a lot of the image / gallery content from the commonplace theme / site were not copied over.  I updated the homepage and the first story with the images (manually copied over from the commonplace site) - so check those for accuracy.
