### ISSUE TITLE
Cover 

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#40]
Hi Jim,

Wanted to get this on your radar as i know you are heading out of town soonish. I will send a comp in the morning (tragic laptop death-by-coffee event slowing me down a bit today).

We essentially realized that the cover of the magazine (landing page) is redundant - future economy, future economy - and what we would like to do is have the logo be much larger, delete the knockout title, and turn "issue" into a few sentences of teaser text enticing the reader to scroll down. And add a white circle behind the orange arrow. Comp coming in the morning.

Does this sound doable in the short timeline we have left? Ideally the "issue" text could become an editable field.

Thanks! Sarah

**Comment by ghost** [comment]
Yeah - get me the comp ASAP and I'll put it together before the end of today.

**Comment by sarahmagrish** [comment]
Will do! By 1pm today.

Sarah Cline | Design Director | Ecotrust
721 NW 9th Avenue, Suite 200 |  Portland, OR 97209
M (971) 344.7595 | www.ecotrust.org

**Comment by sarahmagrish** [comment]
ok! assets are coming via email - can't attach .ai files here. Comp here as screenshot. 
![screen shot 2015-01-28 at 1 51 27 pm](https://cloud.githubusercontent.com/assets/4765127/5947803/cb852422-a6f4-11e4-9153-c95ce2978ee3.png)
I optimized the logo for a larger display and we just nixed any other text on that cover page. added in white circle behind orange arrow. would be good to do that to all orange arrows time permitting. cover would be priority tho.

**Comment by ghost** [comment]
Okay. I’ll see what I can get done in the next couple hours.  

Thanks.  

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)

**Comment by ghost** [comment]
Take a look and let me know what you think.

**Comment by sarahmagrish** [comment]
so close! can you bring down arrow + circle by 50 - 60% and add a drop shadow (not detectable but just to pop the text) to the future economy?

**Comment by ghost** [comment]
Okay. How is that?

**Comment by sarahmagrish** [comment]
great - closing both tickets down! thx

Sarah Cline | Design Director | Ecotrust
721 NW 9th Avenue, Suite 200 |  Portland, OR 97209
M (971) 344.7595 | www.ecotrust.org
