### ISSUE TITLE
last thing! line spacing on story titles

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#41]
can you tighten line spacing on Knockout titles on cover pages up a bit? The leading / line spacing is too open - see http://commonplacemagazine.org/new-pioneers/los-pioneros/ title for reference on proper spacing.

last thing - for real. thx

**Comment by ghost** [comment]
See if that is any better (make sure to reload)

**Comment by sarahmagrish** [comment]
line spacing looks great. same comment on arrow + circle as cover - down by 50 - 60%
