### ISSUE TITLE
Author credit options

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#42]
When you get back, could you add "Illustration" as one of the options under Contribution in the author field under Story Meta? Thanks! (And let me know where you are on hours! If we need to make a contract for more, we can.) 
![2015-01-30 17_32_30-greenshot](https://cloud.githubusercontent.com/assets/10564459/5986244/041bdfee-a8a6-11e4-96d4-9db524770b25.png)

**Comment by ghost** [comment]
Okay. Illustration has been added. 

Please confirm that it is showing correctly when selected.

**Comment by lmilholland** [comment]
It is showing up correctly!
