### ISSUE TITLE
TOC alignment

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#43]
Hi Jim,

I think this was something that was never resolved in the original commonplace template but as I add TOC images they don't align - Ihave made them all the same dimensions tho. Can you see what is going on in the code? possible to align the top of the images? then if text length is different it can vary from there?

![screen shot 2015-02-02 at 8 17 06 am](https://cloud.githubusercontent.com/assets/4765127/6003915/292ff72e-aab4-11e4-8b27-c1c366513088.png)

**Comment by ghost** [comment]
It looks like there was some custom styling on these boxes - maybe to align pictures that were NOT the same size?  I'll remove those custom styles... to align them top.

![new-pioneers_less_ _future_economy](https://cloud.githubusercontent.com/assets/886931/6011491/3c94fc1e-aaf1-11e4-92fb-e656b10d7686.png)

**Comment by ghost** [comment]
There you go - should be fixed now.

**Comment by lmilholland** [comment]
Sweet!
