### ISSUE TITLE
white-on-white

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#44]
is it possible to make the hamburger menu icon and the "about" dark grey here? otherwise they are barely visible. open to other fixes too!

![screen shot 2015-02-01 at 11 34 09 pm](https://cloud.githubusercontent.com/assets/4765127/6003935/4df507e8-aab4-11e4-8939-32969f31c638.png)

**Comment by ghost** [comment]
That was actually my mistake - there was a style in the stylesheet that was using "about-commonplace" but needed to be changed in all instances to about-future-economy.

I made the change and the header shows on the about page as it does when you scroll down.  Looks better. Does that work for you?

**Comment by sarahmagrish** [comment]
yep, great
