### ISSUE TITLE
Larger TOC intro / dek

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#45]
can we bump the size up 150% and close up the line height a bit? comp attached! also shows the TOC images more or less aligned via photoshop for reference. thx.

![screen shot 2015-02-02 at 8 24 53 am](https://cloud.githubusercontent.com/assets/4765127/6004086/2ccbf058-aab5-11e4-921c-780f7f884547.png)

**Comment by ghost** [comment]
Okay. How is that?

**Comment by sarahmagrish** [comment]
perfect.
