### ISSUE TITLE
Sidebar photo is not turning round

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#48]
In the original template (and when I was testing earlier, I think) the sidebar images would show us as circles. When we uploaded a perfect square, they would show up unwarped as clean circles. But now, for some reason, the images are showing up as squares. Can you please return them to circles? Thanks! (This is the story where I am playing: http://www.futureecon.org/future-economy/reach-local-foods/)
![2015-02-04 10_24_39-greenshot](https://cloud.githubusercontent.com/assets/10564459/6046545/1a3ce402-ac58-11e4-8f63-f88992e7e86a.png)
![2015-02-04 10_24_53-greenshot](https://cloud.githubusercontent.com/assets/10564459/6046546/1a3e553a-ac58-11e4-97b8-38814485b294.png)
p.s. invoice being submitted today!

**Comment by ghost** [comment]
So... try this. Instead of selecting "Graphic" - select "image"

Apparently graphic removes the roundness and makes it square (used for graphics you don't want to be round).

![edit_post_ _future_economy_ _wordpress](https://cloud.githubusercontent.com/assets/886931/6112501/551901a0-b045-11e4-81bb-3dd60fb24b93.png)

**Comment by lmilholland** [comment]
When I do that, it makes the name clickable and wants to open a lightbox image. I don't want this to open a larger image, but just be as it was, but round. Possible to do that? I'm worried we never intended to do that with Commonplace, and that's why it's like this. In my dream world, I would be able to click a box when I want the graphic to be round. 
![2015-02-09 12_42_18-greenshot](https://cloud.githubusercontent.com/assets/10564459/6115282/626513a8-b059-11e4-80f4-836401dd499f.png)

**Comment by ghost** [comment]
Ask and you shall receive.  ^_^  

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)

**Comment by ghost** [comment]
Okay.  There is now a "Round Image" option.

**Comment by lmilholland** [comment]
Dreams come true!
