### ISSUE TITLE
Knockout in the deks

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#5]
Probably the same knockout issue we are seeing elsewhere...screenshots attached from the style sheet and then the browser - Mac / Chrome again.
![screen shot 2015-01-16 at 12 41 22 pm](https://cloud.githubusercontent.com/assets/4765127/5784000/286fd7ee-9d7d-11e4-8f2b-1d82ad3277e1.png)
![screen shot 2015-01-16 at 12 42 04 pm](https://cloud.githubusercontent.com/assets/4765127/5784001/287135a8-9d7d-11e4-93b4-e66c49d6ea03.png)

**Comment by ghost** [comment]
This should be fixed now.
