### ISSUE TITLE
Researchers credit

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#51]
Hey Sarah,

We are getting feedback from researchers that they feel they are not getting adequate credit for their work. Oakley wondered whether we could add a "Research by" byline at the top, below the story title. I thought perhaps we just add their name as a credit line, and then include their bio at the bottom with the "Research by" intro. I feel like if we're going to made a secondary byline up top, you should think about the design. Same with if the TOC is going to have a Research by line. But, we could do the simplier thing of just adding them as an author. Your call! I want you to make the decision that feels right, visually. Once you decide, if we need to work with Jim to adapt things, we can. THanks!

**Comment by sarahmagrish** [comment]
let's just add as a third author and credit in the bottom bios. work for you? can we add a third name?
