### ISSUE TITLE
Author list - weighing solutions

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#52]
So we've come to a problem where we have more than 2 authors for several stories (because we're adding the researchers) and now it looks crummy because an & sign appears between their names (see screen shots.) What's the best solution? Easy to put a comma between and first and second name? OR, alternately, easy to be able to check a box that makes one of them appear in the bio section, but disappear from the header and Table of Contents? What do you think would work best, Jim? Thanks!
![2015-02-06 13_10_30-greenshot](https://cloud.githubusercontent.com/assets/10564459/6088029/2b372c4e-ae07-11e4-8b7e-5ee107e615ae.png)
![2015-02-06 13_10_45-greenshot](https://cloud.githubusercontent.com/assets/10564459/6088030/2b389200-ae07-11e4-9e91-ce5fb381652d.png)

**Comment by ghost** [comment]
I'll make it so that it adds comma's if more than 2 (with & between the last two), or just & for two. 
Then you can tell me if that looks okay, and if not I can just show the first author on this page...

**Comment by ghost** [comment]
Okay - you can go ahead and check that fix out now and let me know what you think.

**Comment by lmilholland** [comment]
Great. Fixed in the TOC. For whatever reason, the comma change isn't showing up in the sidebar table of contents. It's still all & signs. And similarly, in the
![2015-02-09 12_35_34-greenshot](https://cloud.githubusercontent.com/assets/10564459/6115173/6fb15766-b058-11e4-831d-f72d73cc3414.png)
![2015-02-09 12_36_57-greenshot](https://cloud.githubusercontent.com/assets/10564459/6115172/6fb0a2e4-b058-11e4-918d-103174a54fe7.png)

 stories themselves

**Comment by ghost** [comment]
Yep I didn't even think about that - I'll fix em up

**Comment by ghost** [comment]
Okay.

This should be fixed now - although I found that going to futureecon.org it wasn't updating - but when I switched to www.futureecon.org it was.

Again, I'm not sure what's going on there... something to do with caching I think on the subdomain www vs no subdomain (just futureecon.org)

Qustion for IT I guess...
