### ISSUE TITLE
i for info on the cover images

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#53]
Hi Jim, Is it possible to get these little information boxes to grow to the size of the caption I want to include? See bottom right corner here. 
![2015-02-06 15_55_21-greenshot](https://cloud.githubusercontent.com/assets/10564459/6089519/c05c15ee-ae18-11e4-8250-0964c38ae4e9.png)

**Comment by lmilholland** [comment]
Can you also remove the "Photo By" entirely? So just the attribution appears? That's fine with me for all the photos, if that's easiest, but it's most important here.

**Comment by ghost** [comment]
Okay, I'll see what I can do. FYI - it appears it doesn't work on commonplace either...

**Comment by ghost** [comment]
Oh! You know what... you have to click on it to see the whole thing - apparently when you hover it shows a little, and then when you click it shows the entire thing. Do you want to change this functionality?

**Comment by lmilholland** [comment]
When I click, it doesn't show the whole thing! It just jumps out and then retracts, always showing a partial caption. I'd like it to show the whole thing. I don't care if it's with a hover or click. Ideally with the hover it would show the whole thing til you moved your mouse, and with the click it would show the whole thing until you clicked again. Sound right? Possible?

Sent from my iPhone

On Feb 9, 2015, at 9:51 AM, Jim Krill <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh! You know what... you have to click on it to see the whole thing - apparently when you hover it shows a little, and then when you click it shows the entire thing. Do you want to change this functionality?

##

**Comment by ghost** [comment]
Yeah that sounds right. Let me see what I can do.  

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)

**Comment by ghost** [comment]
Okay - see how that works for you.

There were two problems... one being the functionality, but the other was that it had a set width and height and so was not working with such a long attribution.  I changed it to have auto height, so test it out on the photos you have and see if that's any better or needs any tweaking.

**Comment by lmilholland** [comment]
It looks great! I like the functionality now. I'm wondering, though, if you can remove the "photo by" at the opening. It's a long story, but specifically for the home page, it would be great if we could do a caption, no credit.
