### ISSUE TITLE
Knockout in pull quotes

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#6]
Probably the same knockout issue we are seeing elsewhere...screenshots attached from the style sheet and then the browser - Mac / Chrome again.

![screen shot 2015-01-16 at 12 43 35 pm](https://cloud.githubusercontent.com/assets/4765127/5784035/6a64ff3a-9d7d-11e4-8f79-6ebc6871418e.png)
![screen shot 2015-01-16 at 12 44 07 pm](https://cloud.githubusercontent.com/assets/4765127/5784036/6a66a02e-9d7d-11e4-854b-adfb87b06308.png)

**Comment by ghost** [comment]
Should be fixed.
