### ISSUE TITLE
Author names in menu

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#7]
Should be sentinel
![screen shot 2015-01-16 at 12 45 09 pm](https://cloud.githubusercontent.com/assets/4765127/5784052/8ca0da24-9d7d-11e4-880b-4fab234eb318.png)

**Comment by ghost** [comment]
Should be fixed.

**Comment by lmilholland** [comment]
Looks good - now it's sentinel. Please remove the bold on author names in menu.

**Comment by ghost** [comment]
Okay. Fixed.
