### ISSUE TITLE
Removing "Issues" page

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#8]
Since this project does not involve multiple issues, we should remove the "issues" link from the top of the content navigation bar at left. See the attached - where my mouse is pointing. (I hope it works!)

![2015-01-16 15_40_08-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786229/68a59588-9d96-11e4-87e8-487d0eb86cf9.jpg)

**Comment by ghost** [comment]
Okay, this was removed.
