### ISSUE TITLE
sidebar content in stories - safari and chrome, pc

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#9]
In safari and chrome on my pc, all of the stories' sidebar content is coming across as wonky code. An example of what these two look like on commonplace below for reference.
![2015-01-16 15_44_49-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786250/c8d004a2-9d96-11e4-8e6a-bff08a096218.jpg)
![2015-01-16 15_45_24-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786251/c8d35cd8-9d96-11e4-965e-4c61cf35493a.jpg)
![2015-01-16 15_48_41-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786273/312f3590-9d97-11e4-80c9-ee7cb8b331ee.jpg)
![2015-01-16 15_48_51-greenshot](https://cloud.githubusercontent.com/assets/10564459/5786274/3131dc96-9d97-11e4-9563-2ab5d75421ff.jpg)

**Comment by ghost** [comment]
Again, all of the images / galleries were not copied over with the content from Commonplace.  They will either need to be manually copied over or just update the content with the Future Economy content / images / and galleries.
